### ISSUE TITLE
how to define an error respond ？

### ISSUE THREAD

**Issue by xiaojingzhao** [spreaker/node-mock-http-server#10]
what if I want 401, 302 or any custom error?

**Comment by xiaojingzhao** [comment]
sorry, I know how to define error now

**Comment by tracy-ash** [comment]
How do I set the `reply.status` and `reply.body` for a POST so that the value of `reply.status` depends on the outcome of the function called by 'reply.body`?

I've tried something like this, but it doesn't work:

```
function postFunction(){
  const bodyString = JSON.stringify({this: "OK"})
  return { status: 401, headers: { "content-type": "application/json" }, body: bodyString}
}

server.on({
  method: "POST",
  path: "/",
  reply: postFunction,
});
```
