### ISSUE TITLE
requests method uses OR logic to filter by method and path

### ISSUE THREAD

**Issue by adaniline** [spreaker/node-mock-http-server#13]
The documentation gives an example that implies that the requests should be filtered using AND logic:
```
// Returns all GET requests to /resource
server.requests({ method: "GET", path: "/resource" });
```
However the implementation of requests method uses "OR" logic to filter requests by method and path

**Comment by pracucci** [comment]
Hi @adaniline. I quickly re-checked the code and I believe you're referring this this piece of code:

```
            // Check if we can handle the request
            if (handled ||
              (handler.method != "*" && req.method != handler.method.toUpperCase()) ||
              (handler.path != "*" && reqParts.pathname != handler.path) ||
              (handler.filter && handler.filter(req) !== true)) {
                return;
            }
```

However, the code above is a guard, that means if method doesn't match or path doesn't match or filter doesn't match, that do **not** handle it, so basically path and method are in a AND condition. Am I missing anything?

Thank you,
Marco

**Comment by pracucci** [comment]
_Closing due to no reply, but feel free to re-open if you wanna follow up. Thanks!_
