### ISSUE TITLE
How to get body of an HTTP request?

### ISSUE THREAD

**Issue by mushketyk** [spreaker/node-mock-http-server#14]
The documentation provides a way to get requests sent to a mock server, e.g.:

```javascript
// Returns all requests
server.requests();
```

But it does not specify how to get a body of a request.

Could you update documentation and provide examples how to get more information about a request, e.g. body, headers, etc.

**Comment by pracucci** [comment]
@mushketyk Sorry for the very late reply. The request body is stored in the property `request.body` and before version 1.1.0 only JSON-encoded bodies were parsed. Today I've released version [`1.1.0`](https://github.com/spreaker/node-mock-http-server/releases/tag/1.1.0) which also add supports for urlencoded bodies. May you check if it works to you, please?

**Comment by pracucci** [comment]
_I'm closing the issue since it should have been fixed now, but feel free to re-open in case it's not. Thanks!_
