### ISSUE TITLE
Request body is not preserved

### ISSUE THREAD

**Issue by mushketyk** [spreaker/node-mock-http-server#15]
I am trying to verify if a POST request was performed with a correct request body. Here is my test setup:

```
describe('Client', () => {
  const server = new ServerMock({ host: 'localhost', port: 9001 })

  beforeEach(function(done) {
    server.start(done)
  })

  afterEach(function(done) {
    server.stop(done)
  })

   it('test', async done => {
    server.on({
      method: 'POST',
      path: '/path',
      reply: {
        status: 200,
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({})
      }
    })

    // Perfrom POST request
    axios.post(...)

    const requests = server.requests({ method: 'POST', path: '/path' })
    // This assert passes
    expect(requests.length).toEqual(1)
    // This assert fails since "requests[0].body" is undefined
    expect(requests[0].body).toEqual({
      id: 5
    })
    done()
  })

})
```

Despite the fact that body is sent with the request (checked with Wireshark) it is not preserved on a request object.

**Comment by hannupekka** [comment]
In my case request has content-type header with value `application/json; charset=utf-8` so https://github.com/spreaker/node-mock-http-server/blob/master/src/server.js#L74 skips parsing request body.

There is a PR which should resolve this: https://github.com/spreaker/node-mock-http-server/pull/16

**Comment by pracucci** [comment]
@hannupekka I've just released version [`1.1.0`](https://github.com/spreaker/node-mock-http-server/releases/tag/1.1.0) which includes the PR #16 and should solve your issue. May you try again and let me know, please?

**Comment by hannupekka** [comment]
Seems to work now, thanks!

**Comment by pracucci** [comment]
Thanks for the reply. I'm then closing this issue, but feel free to re-open it in case the PR #16 doesn't fully solve your use case.
