### ISSUE TITLE
Add the ability to set a random port number

### ISSUE THREAD

**Issue by Nautigsam** [spreaker/node-mock-http-server#17]
For my tests I don't like to choose a port number myself. I prefer to let the system to assign me a random port number. Since `mock-http-server` uses `http.Server` under the hood, I am able to set port number as 0, but I can not get the assigned port number back. It would be great that the server instance expose this information.

**Comment by pracucci** [comment]
@Nautigsam Are you willing to submit a PR for it?

**Comment by Nautigsam** [comment]
Sure, I will work on it and let you know.
