### ISSUE TITLE
[question] Handler overrides

### ISSUE THREAD

**Issue by ghost** [spreaker/node-mock-http-server#2]
Hi, is there any way to override a handler using the "on(...)" method? I saw that handlers are pushed into an array, and then, if a new handler for the same kind of request is pushed, the previous one takes precedence. 
If [this array push](https://github.com/spreaker/node-mock-http-server/blob/master/src/server.js#L254) is changed to a "unshift" operation the new handlers will be found first when filtering to handle a mocked request. What do you think?

**Comment by pracucci** [comment]
You're right and your suggestion makes sense to me. Are you willing to submit a PR with the change, please?
