### ISSUE TITLE
Add a method which returns all unmatched requests

### ISSUE THREAD

**Issue by znerol** [spreaker/node-mock-http-server#4]
It is sometimes useful to verify that no unexpected requests are triggered while exercising a test case. Hence I suggest to add a method which simply returns all unmatched requests.

**Comment by pracucci** [comment]
Hi znerol, sorry for the super late reply. I'm currently not actively working on this project (even if I'm still using it on several other projects). Do you have time to submit a PR for your feature request? I will be very happy (and much faster) to review it.

**Comment by znerol** [comment]
I'm not using it neither atm.

**Comment by pracucci** [comment]
Ok, so I'm going to close the request. Feel free to re-open it, in case you will need it again.
